name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Rename sample.config.json to config.json
        run: cat sample.config.json > config.json
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
