on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Run tests
        run: go test -v ./...